install package after setup config files
hagihala/cookbook-varnish pull request #2
Opened 2018-07-11 03:38 UTC by nabeo

postinst file included in varnish package try to launch varnishd.
because vcl_conf is not ready, varnishd faild to launch.

2018-07-11 07:21 UTC, hagihala requested changes

2018-07-11 07:21 UTC, hagihala commented on recipes/default.rb
> -
`template "#{node['varnish']['dir']}/#{node['varnish']['vcl_conf']}"` needs `directory "#{node['varnish']['dir']}/"` to be created before it.

2018-07-13 08:26 UTC, nabeo commented
@hagihala i fixed your suggestion. and I confirmed that it works correctly in my environment.

2018-07-18 01:36 UTC, hagihala approved these changes

2018-07-18 01:36 UTC, merged